### ISSUE TITLE
"Thread.exclusive is deprecated, use Mutex"

### ISSUE THREAD

**Issue by matkoniecz** [endymion/link-checker#23]
spammed on simplest possible use

**Comment by upgundecha** [comment]
Getting same error while running against a live site

**Comment by ellisonch** [comment]
Have the same problem:

```
$ check-links
Thread.exclusive is deprecated, use Mutex
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:176:in `report_results'
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:159:in `block in check_page'
Checked: ./_includes/analytics.htmlThread.exclusive is deprecated, use Mutex
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:176:in `report_results'
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:159:in `block in check_page'

Checked: ./_includes/footer.html
Thread.exclusive is deprecated, use MutexThread.exclusive is deprecated, use Mutex
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:176:in `report_results'
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:159:in `block in check_page'
Checked: ./_includes/posts.html

.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:176:in `report_results'
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:159:in `block in check_page'Thread.exclusive is deprecated, use Mutex
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:176:in `report_results'
.../.gem/ruby/2.3.0/gems/link-checker-0.7.2/lib/link_checker.rb:159:in `block in check_page'
```

**Comment by danhalligan** [comment]
Same issue here.

**Comment by ramosmd** [comment]
same for me

**Comment by hjerpbakk** [comment]
Same here
